name: task_manager_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # connection
  dio: ^5.4.3+1

  # local storage
  shared_preferences: ^2.2.3

  # state management
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5

  # navigation
  go_router: ^14.0.1

  # dependency injection
  get_it: ^7.6.7

  # utils
  equatable: ^2.0.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  top_snackbar_flutter: ^3.0.0

  # test
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  build_runner: ^2.3.3
  connectivity_plus: ^2.3.0


flutter:
  uses-material-design: true
